#!/bin/bash

# A script that will ask for a value and print out a message depending on the value. 

read -p "Enter a value: " n
case $n in
    1) 
        echo "One";;
    2) 
        echo "Two";;
    3) 
        echo "Three";;
    *.txt) 
        echo "$n is a text file";;
    *) 
        echo "Other";;
esac
    