#!/bin/bash

number=254

if [ $((number % 2)) -eq 0 ];
#double opening and closing brackets for condition computation
then
   echo "The number $number is even!";
else 
   echo "The number $number is odd!"
fi
