#!/bin/bash

check_even () {
    local mod=2
    echo "The value of mod is $mod"
    if [ $(("$2" % $mod)) -eq 0 ]
    then 
       echo "The number $2 is even!";
    else 
       echo "The number $2 is odd!"
    fi
}


number=99
numbers=23445
check_even $numbers $number 
echo $mod